name: solar system
on:
   workflow_dispatch: 
   push:
     branches: 
     - main
     - feature/*

jobs:
    unit-testing:
    name: nodejs unit testing
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4


    